atividade/urls.py
from django.contrib import admin
from django.urls import path
from atividade.views import adicionar_manutencao, escolher_manutencao, \
    acompanhar_manutencao_view, adicionar_atividade, editar_manutencao, excluir_atividade, detalhes_manutencao_view, \
    salvar_comentario, salvar_foto, alterar_status, item_detail, alterar_status_item, alterar_data_manutencao
from django.conf import settings
from django.conf.urls.static import static
app_name = 'atividade'

urlpatterns = [
    path('item_detail/<int:item_id>/', item_detail, name='item_detail'),
    path('alterar_status/<int:atividade_id>/', alterar_status, name='alterar_status'),
    path('salvar-comentario/<int:item_id>/', salvar_comentario, name='salvar_comentario'),
    path('salvar-foto/<int:item_id>/<str:foto_field>/', salvar_foto, name='salvar_foto'),
    # path('alterar-data-manutencao/<int:manutencao_id>/', alterar_data_manutencao, name='alterar_data_manutencao'),
    path('adicionar-manutencao/', adicionar_manutencao, name='adicionar_manutencao'),
    path('adicionar_atividade/<int:manutencao_id>/', adicionar_atividade, name='adicionar_atividade'),
    path('escolher_manutencao/', escolher_manutencao, name='escolher_manutencao'),
    path('alterar_data_manutencao/', alterar_data_manutencao, name='alterar_data_manutencao'),
    path('excluir/<int:area_id>/', excluir_atividade, name='excluir_atividade'),
    path('acompanhar-manutencao/', acompanhar_manutencao_view, name='acompanhar_manutencao'),
    path('editar_manutencao/<int:manutencao_id>/', editar_manutencao, name='editar_manutencao'),
    path('detalhes-manutencao/<int:manutencao_id>/', detalhes_manutencao_view, name='detalhes_manutencao'),
    path('alterar_status_item/<int:id>', alterar_status_item, name='alterar_status_item'),
]

empresa/urls.py
from django.contrib import admin
from django.urls import path
from empresa.views import cadastro_empresa, editar_empresa, listar_empresas
from django.conf import settings
from django.conf.urls.static import static
app_name = 'empresa'

urlpatterns = [

    path('cadastro_empresa/', cadastro_empresa, name='cadastro_empresa'),
    path('editar_empresa/<int:empresa_id>/', editar_empresa, name='editar_empresa'),
    path('listar_empresas/', listar_empresas, name='listar_empresas'),

]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from usuario.views import signup_view, home, login_view
from atividade.views import excluir_atividade
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.contrib.staticfiles.views import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup_view, name='signup'),
    path('', home, name='home'),
    path('atividade/', include('atividade.urls', namespace='atividade')),
    path('empresa/', include('empresa.urls', namespace='empresa')),
    path('excluir/<int:area_id>/', excluir_atividade, name='excluir_atividade'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/models.py
from django.db import models
from django.urls import reverse

class Empresa(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=200)
    telefone = models.CharField(max_length=20)
    cpf_cnpj = models.CharField(max_length=20, unique=True, null=True, blank=True)


    def __str__(self):
        return self.nome

class Manutencao(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    data_manutencao = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('atividade:atividades_empresa', args=[str(self.empresa.id)])


    def __str__(self):
        return f"Manutenção para {self.empresa.nome}"

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from pycpfcnpj import cpfcnpj

class UserProfileForm(UserCreationForm):
    cpf_cnpj = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def clean_cpf_cnpj(self):
        cpf_cnpj = self.cleaned_data['cpf_cnpj']

        # Verificar se o CPF/CNPJ é válido
        if not cpfcnpj.validate(cpf_cnpj):
            raise forms.ValidationError("CPF/CNPJ inválido.")

        return cpf_cnpj

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user_profile = UserProfile(user=user, cpf_cnpj=self.cleaned_data['cpf_cnpj'])

        if commit:
            user.save()
            user_profile.save()

        return user, user_profile

templates/adicionar_manutencao.html
<!-- adicionar_manutencao.html -->
{% extends "base_generic.html" %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-5">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">Adicionar Manutenção Preventiva</h4>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_empresa">Empresa:</label>
            {{ form.empresa }}
          </div>
          <div class="form-group">
            <label for="id_data_manutencao">Data da Manutenção:</label>
            {{ form.data_manutencao }}
          </div>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
      </div>
      <div class="card-footer">
        <a href="{% url 'home' %}" class="btn btn-secondary">Voltar para a Home</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cadastro_empresa.html
<!-- cadastro_empresa.html -->
{% extends "base_generic.html" %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-5">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">Cadastro de Empresa</h4>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
      </div>
      <div class="card-footer">
        <a href="{% url 'home' %}" class="btn btn-secondary">Voltar para a Home</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/detalhes_manutencao_2.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card mt-3 mb-3">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <i class="fas fa-tasks"></i> Detalhes da Manutenção
        </h4>
      </div>
      <div class="card-body">
        <h5 class="card-title">Manutenção: #{{ manutencao.id }} <br> Empresa: {{ manutencao.empresa.nome }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">Data: {{ manutencao.data_manutencao|date:"d M, Y" }}</h6>
        <p class="card-text mb-3">{{ manutencao.descricao }}</p>

        <h3 class="mb-3">Áreas:</h3>
        <ul class="list-group">
          {% for atividade in atividades %}
          <li class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
              <h4 class="my-2">{{ atividade.area }}
              {% if atividade.status == "Pendente" %}
              <span class="badge badge-danger">Pendente</span>
                {% else %}
              <span class="badge badge-success">Concluido</span>
                {% endif %}</h4>

              <h6 class="my-2">itens concluidos {{ atividade.checka }} de {{ atividade.items_total }}</h6>

              <button class="btn btn-link p-0 btn-toggle" type="button" data-toggle="collapse" data-target="#atividade{{ atividade.id }}" aria-expanded="false" aria-controls="atividade{{ atividade.id }}">
                <i class="fas fa-chevron-down"></i>
              </button>
            </div>
            <div class="collapse mt-3" id="atividade{{ atividade.id }}">
              <form method="post" action="{% url 'atividade:alterar_status' atividade.id %}">
                {% csrf_token %}
                <div class="input-group mb-3">
                  <select class="form-select" name="status">
                    <option value="Pendente" {% if atividade.status == 'Pendente' %} selected {% endif %}>Pendente</option>
                    <option value="Concluído" {% if atividade.status == 'Concluído' %} selected {% endif %}>Concluído</option>
                  </select>
                  <button type="submit" class="btn btn-primary ml-3">Salvar Status</button>
                </div>
              </form>
              <h4 class="my-3">Itens:</h4>
              {% for item in itens %}
              {% if item.atividade == atividade %}

              <div class="mt-3">
                <div class="d-flex justify-content-between align-items-center">
                  <!-- Instead of using a button to toggle visibility, we now link to a new page -->
                  <a href="{% url 'atividade:item_detail' item.id %}"><h6>{{ item.descricao }} </h6></a>
                   <h4>{% if item.status == "Pendente" %}
              <span class="badge badge-danger">Pendente</span>
                {% else %}
              <span class="badge badge-success">Concluido</span>
                {% endif %}</h4>
                </div>
                <hr> <!-- Adding a line to separate items -->
              </div>
              {% endif %}
              {% endfor %}
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/editar_manutencao.html
{% extends "base_generic.html" %}

{% block content %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <div class="container">
    <div class="card mt-5">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <i class="fas fa-edit"></i> Editar Manutenção
        </h4>
      </div>
      <div class="card-body">
  <form id="manutencaoForm" method="post" action="{% url 'atividade:editar_manutencao' manutencao.id %}">
    {% csrf_token %}
    <h5 class="card-title">Manutenção: {{ manutencao }}</h5>
    {% for area in area_choises %}
      {% for atividade in atividades %}
        {% if atividade.area == area.nome %}
          <div class="card mt-3">
            <div class="card-header bg-primary text-white">
              <h5 class="mb-0">
                <span class="circle-icon"><i class="fas fa-edit"></i></span> Editar Atividade: {{ area }}
                <button class="btn btn-danger float-right" onclick="excluirAtividade({{ atividade.id }})">Excluir</button>
              </h5>
            </div>
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">Itens:</h6>
              {% for item in area.itemchoise_set.all %}
        <div class="form-check">
            <input class="form-check-input item-checkbox" type="checkbox" name="item_{{ atividade.id }}_{{ item.id }}" value="{{ item.id }}"

                {% for atividade_item in atividade.item_set.all %}
                    {% if item.nome == atividade_item.descricao %}
                        checked
                    {% endif %}
                {% endfor %}>
            <label class="form-check-label" for="item_{{ item.id }}">{{ item }}</label>
        </div>
    {% endfor %}
            </div>
          </div>
        {% endif %}
        <input type="hidden" id="item_ids_{{ atividade.id }}" name="item_{{ atividade.id }}_ids">
      {% endfor %}
    {% endfor %}
    <button type="submit" class="btn btn-primary mt-3">Salvar</button>
  </form>
</div>
<script>
    $(document).ready(function() {
        $('#manutencaoForm').on('submit', function(e) {
            $('.item-checkbox:checked').each(function() {
                var atividadeId = this.name.split('_')[1];
                var itemIds = $('#item_ids_' + atividadeId).val();
                itemIds = itemIds ? itemIds.split(',') : [];
                itemIds.push($(this).val());
                $('#item_ids_' + atividadeId).val(itemIds.join());
            });
        });
    });
</script>




      <div class="card-footer">
        <a href="{% url 'home' %}" class="btn btn-primary">Voltar para a Home</a>
      </div>
    </div>

    <div class="card mt-5">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">Adicionar Itens</h4>
      </div>
      <div class="card-body">
        <form id="adicionarItensForm" method="post" action="{% url 'atividade:adicionar_atividade' manutencao.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_area">Área:</label>
            <select class="form-control" id="areaSelect" name="area">
              <option value="">Selecione uma área...</option>
              {% for area in area_choises_add %}
                <option value="{{ area.id }}">{{ area.nome }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label for="id_status">Status:</label>
            <select class="form-control" id="statusSelect" name="status">
              <option value="">Selecione um status...</option>
              <option value="Pendente">Pendente</option>
              <option value="Concluído">Concluído</option>
            </select>
          </div>
          <div class="form-group" id="itensDiv" style="display: none;">
            <label for="id_itens">Itens:</label>
            {% for area in area_choises_add %}
              <div id="itens{{ area.id }}" style="display: none;">
                {% for item in area.itemchoise_set.all %}
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="itens[]" value="{{ item.id }}" id="item{{ item.id }}">
                    <label class="form-check-label" for="item{{ item.id }}">{{ item.nome }}</label>
                  </div>
                {% endfor %}
              </div>
            {% endfor %}
          </div>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
      </div>
    </div>
  </div>


  <script>
    $(document).ready(function() {
      // Ativa a seleção de itens quando uma área é selecionada
      $('#areaSelect').change(function() {
        $('#itensDiv').hide();
        $('div[id^="itens"]').hide();
        if ($(this).val() !== "") {
          $('#itensDiv').show();
          $('#itens' + $(this).val()).show();
        }
      });
    });

    // Configura o AJAX globalmente para sempre enviar o token CSRF
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        }
      }
    });

    var baseURL = "{% url 'atividade:excluir_atividade' 0 %}";

    function excluirAtividade(areaId) {
      console.log('excluirAtividade chamada com id:', areaId);

      var url = baseURL.replace('0', areaId);

      console.log('URL: ', url);
      $.ajax({
        url: url,
        type: 'POST',
        data: {
          'csrfmiddlewaretoken': '{{ csrf_token }}',
          'delete': 'true'
        },
        success: function() {
          location.reload();
        },
        error: function(error) {
          console.error('Erro:', error);
        }
      });
    }
  </script>
{% endblock %}

templates/editar_manutencao2.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="section-header mt-5">
    <h1 class="h3 h1-lg">Editar Manutenção</h1>
    <h2 class="h5 h2-lg mt-2">Manutenção: {{ manutencao }}</h2>
  </div>

  <div class="container-sm">
    <form method="post">
      {% csrf_token %}
      {% for area in area_choises %}
      {% for atividade in atividades %}
        {% if atividade.area == area.nome %}
          <div class="card mt-5">
            <div class="card-header bg-primary text-white">
              <h4 class="mb-0">
                <span class="circle-icon"><i class="fas fa-edit"></i></span> Editar Atividade: {{ area }}
                <button class="btn btn-danger float-right" onclick="excluirAtividade({{ atividade.id }})">Excluir</button>
              </h4>
            </div>
            <div class="card-body">
              <h5>Itens:</h5>
              {% for item in area.itemchoise_set.all %}
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" name="itens_{{ area.id }}" value="{{ item_choice.id }}"
              {% for atividade_item in atividade.item_set.all %}
                {% if item.nome == atividade_item.descricao %}
                  checked
                {% endif %}
              {% endfor %}>
                  <label class="form-check-label" for="itens_{{ area.id }}">{{ item }}</label>
                </div>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>


 <!-- Formulário para adicionar itens -->
  <div class="card mt-5">
    <div class="card-header bg-primary text-white">
      <h4 class="mb-0">Adicionar Itens</h4>
    </div>
    <div class="card-body">
      <form id="adicionarItensForm" method="post" action="{% url 'atividade:adicionar_atividade' manutencao.id %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_area">Área:</label>
          <select class="form-control" id="areaSelect" name="area">
            <option value="">Selecione uma área...</option>
            {% for area in area_choises %}
              <option value="{{ area.id }}">{{ area.nome }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="id_status">Status:</label>
          <select class="form-control" id="statusSelect" name="status">
            <option value="">Selecione um status...</option>
            <option value="Pendente">Pendente</option>
            <option value="Concluído">Concluído</option>
          </select>
        </div>
        <div class="form-group" id="itensDiv" style="display: none;">
          <label for="id_itens">Itens:</label>
          {% for area in area_choises %}
            <div id="itens{{ area.id }}" style="display: none;">
              {% for item in area.itemchoise_set.all %}
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" name="itens[]" value="{{ item.id }}" id="item{{ item.id }}">
                  <label class="form-check-label" for="item{{ item.id }}">{{ item.nome }}</label>
                </div>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
      </form>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script>
    $(document).ready(function() {
      // Ativa a seleção de itens quando uma área é selecionada
      $('#areaSelect').change(function() {
        $('#itensDiv').hide();
        $('div[id^="itens"]').hide();
        if ($(this).val() !== "") {
          $('#itensDiv').show();
          $('#itens' + $(this).val()).show();
        }
      });
    });
  </script>

  <!-- Resto do script... -->

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
// Configura o AJAX globalmente para sempre enviar o token CSRF
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        }
    }
});

var baseURL = "{% url 'atividade:excluir_atividade' 0 %}";



function excluirAtividade(areaId) {
  console.log('excluirAtividade chamada com id:', areaId);

  var url = baseURL.replace('0', areaId);

  console.log('URL: ', url);
  $.ajax({
    url: url,
    type: 'POST',
    data: {
      'csrfmiddlewaretoken': '{{ csrf_token }}',
      'delete': 'true'
    },
    success: function() {
      location.reload();
    },
    error: function(error) {
      console.error('Erro:', error);
    }
  });
}

</script>


{% endblock %}

templates/home.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-1">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <span class="circle-icon" onclick="location.href='{% url 'empresa:cadastro_empresa' %}'"><i class="fas fa-plus-circle"></i></span> Cadastrar Empresa
        </h4>
      </div>
      <div class="card-body">
        <p class="small-text">Cadastre uma nova empresa.</p>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-1">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <span class="circle-icon" onclick="location.href='{% url 'empresa:listar_empresas' %}'"><i class="fas fa-plus-circle"></i></span> Editar Empresa
        </h4>
      </div>
      <div class="card-body">
        <p class="small-text">Edite os dados de uma empresa.</p>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-1">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
<span class="circle-icon" onclick="location.href='{% url 'atividade:adicionar_manutencao' %}'"><i class="fas fa-plus-circle"></i></span> Adicionar Manutenção Preventiva        </h4>
      </div>
      <div class="card-body">
        <p class="small-text">Adicione uma nova manutenção preventiva.</p>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-1">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <span class="circle-icon" onclick="location.href='{% url 'atividade:escolher_manutencao' %}'"><i class="fas fa-plus-circle"></i></span> Editar Manutenção Preventiva
        </h4>
      </div>
      <div class="card-body">
        <p class="small-text">Edite informações da manutenção preventiva.</p>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mt-1">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <span class="circle-icon" onclick="location.href='{% url 'atividade:acompanhar_manutencao' %}'"><i class="fas fa-plus-circle"></i></span> Acompanhar Manutenção Preventiva
        </h4>
      </div>
      <div class="card-body">
        <p class="small-text">Acompanhe as manutenções preventivas executadas ou em andamento.</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/lista_acompanhar_manutencao_preventiva.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card mt-1">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
          <i class="fas fa-tasks"></i> Acompanhar Manutenção Preventiva
        </h4>
      </div>
      <div class="card-body">
        {% for manutencao in manutencoes %}
        <div class="card mt-2">
          <div class="card-body">
            <h5 class="card-title">Manutenção: {{ manutencao.id }} <br> Empresa: {{ manutencao.empresa.nome }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Data: {{ manutencao.data_manutencao|date:"d M, Y" }}</h6>
            <p class="card-text">{{ manutencao.descricao }}</p>
            <a href="{% url 'atividade:detalhes_manutencao' manutencao.id %}" class="card-link">Detalhes</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/signup.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0">Cadastro</h2>
        </div>
        <div class="card-body">
         {% for message in messages %}
            <div class="alert alert-danger mt-3">
              {{ message }}
            </div>
          {% endfor %}
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_username">Nome de usuário:</label>
              <input type="text" name="username" maxlength="150" class="form-control {% if form.username.errors %}is-invalid{% endif %}" required id="id_username">
              {% if form.username.errors %}
                <div class="invalid-feedback">
                  {{ form.username.errors }}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_email">Email:</label>
              <input type="email" name="email" maxlength="254" class="form-control {% if form.email.errors %}is-invalid{% endif %}" required id="id_email">
              {% if form.email.errors %}
                <div class="invalid-feedback">
                  {{ form.email.errors }}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_first_name">Primeiro nome:</label>
              <input type="text" name="first_name" maxlength="30" class="form-control {% if form.first_name.errors %}is-invalid{% endif %}" required id="id_first_name">
              {% if form.first_name.errors %}
                <div class="invalid-feedback">
                  {{ form.first_name.errors }}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_last_name">Sobrenome:</label>
              <input type="text" name="last_name" maxlength="30" class="form-control {% if form.last_name.errors %}is-invalid{% endif %}" required id="id_last_name">
              {% if form.last_name.errors %}
                <div class="invalid-feedback">
                  {{ form.last_name.errors }}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_password1">Senha:</label>
              <input type="password" name="password1" class="form-control" required id="id_password1">
              {% if form.password1.errors %}
                <div class="invalid-feedback">
                  {{ form.password1.errors }}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_password2">Confirme a senha:</label>
              <input type="password" name="password2" class="form-control" required id="id_password2">
              {% if form.password2.errors %}
                <div class="invalid-feedback">
                  {{ form.password2.errors }}
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_cpf_cnpj">CPF/CNPJ:</label>
              <input type="text" name="cpf_cnpj" maxlength="20" class="form-control" required id="id_cpf_cnpj">
              {% if form.cpf_cnpj.errors %}
                <div class="invalid-feedback">
                  {{ form.cpf_cnpj.errors }}
                </div>
              {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
            {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {% for error in form.non_field_errors %}
              {{ error }}
              {% endfor %}
            </div>
            {% endif %}
          </form>
        </div>
        <div class="card-footer text-center">
          <a href="{% url 'login' %}">Já tem uma conta? Faça login</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}